ch=0
while(ch!=5):
	print"*************MENU****************"
	print"1.ADD AND PRINT N STUDENTS NAME ROLL MARKS of 3 SUBJECTS in LIST OF TUPLE"
	print"2.DISPLAY STUDENTS ROLL MARKS WHOSE NAME IS PYTHON"
	print"3.NESTED TUPLE AND SORT IT BY NAME"
	print"4.REPLACE LAST VALUE OF EVERY TUPLE IN LIST AND DISPLAY"
	print"5.EXIT"
	ch=input("ENTER YOUR CHOICE>>>")
	if(ch==1):	
		n=input("ENTER THE NUMBER OF STUDENTS TOU WANT>>>>")
		l=[]
		t=()
		for i in range(0,n):
			nm=input("ENTER THE NAME OF STUDENT>>>>")
			roll=input("ENTER THE ROLLNO OF STUDENT>>>>")
			m1=input("ENTER THE MARKS1 OF STUDENT>>>>")
			m2=input("ENTER THE MARKS2 OF STUDENT>>>>")
			m3=input("ENTER THE MARKS3 OF STUDENT>>>>")
			t=(nm,roll,m1,m2,m3)
			l.append(t)
		print l
	elif(ch==2):
		flag=0
		print"DETAILS OF STUDENT PYTHON IN YOUR LIST"
		for i in range(0,n):
			if(l[i][0]=="PYTHON"):
				print"ROLL NO>>>",l[i][1]
				print"MARKS 1>>>",l[i][2]
				print"MARKS 2>>>",l[i][3]
				print"MARKS 3>>>",l[i][4]		
				flag=1
				break
		if(flag!=1):
			print"NO PYTHON"
	elif(ch==3):
		print"SORTING AS PER NAME"
		a=tuple(l)
		print"THE NEW TUPLE\n",a
		print"SORTED>>>>",sorted(a)
	elif(ch==4):
		print"UPDATING SUBJECT 3 MARKS"
		u=input("ENTER NEW MARKS FOR ALL")
		b=0
		k=[]
		print"OLD LIST\n",l
		for t in l:
			b=t[:-1]+(u,)
			k.append(b)	
		print"NEW LIST\n"
		print k
	elif(ch==5):
		print"EXIT!!"
	else:
		print"INVALID CHOICE"

'''
[student@localhost]$ python exp3atup.py
ENTER THE NUMBER OF STUDENTS TOU WANT>>>>3
ENTER THE NAME OF STUDENT>>>>"HARSH"
ENTER THE ROLLNO OF STUDENT>>>>10
ENTER THE MARKS1 OF STUDENT>>>>80
ENTER THE MARKS2 OF STUDENT>>>>77
ENTER THE MARKS3 OF STUDENT>>>>75
ENTER THE NAME OF STUDENT>>>>"PYTHON"
ENTER THE ROLLNO OF STUDENT>>>>8
ENTER THE MARKS1 OF STUDENT>>>>67
ENTER THE MARKS2 OF STUDENT>>>>56
ENTER THE MARKS3 OF STUDENT>>>>45
ENTER THE NAME OF STUDENT>>>>"DARREL"
ENTER THE ROLLNO OF STUDENT>>>>9
ENTER THE MARKS1 OF STUDENT>>>>80
ENTER THE MARKS2 OF STUDENT>>>>80
ENTER THE MARKS3 OF STUDENT>>>>80
[('HARSH', 10, 80, 77, 75), ('PYTHON', 8, 67, 56, 45), ('DARREL', 9, 80, 80, 80)]
DETAILS OF STUDENT PYTHON IN YOUR LIST
ROLL NO>>> 8
MARKS 1>>> 67
MARKS 2>>> 56
MARKS 3>>> 45

[student@localhost rollno10b]$ python 10exp3a.py
ENTER THE NUMBER OF STUDENTS TOU WANT 1
ENTER THE NAME OF STUDENT>>>>"abs"
ENTER THE ROLLNO OF STUDENT>>>>"3"
ENTER THE MARKS1 OF STUDENT>>>>"12"
ENTER THE MARKS2 OF STUDENT>>>>"23"
ENTER THE MARKS3 OF STUDENT>>>>"34"
[('abs', '3', '12', '23', '34')]
DETAILS OF STUDENT PYTHON IN YOUR LIST
NO PYTHON

SORTING AS PER NAME
THE NEW TUPLE
(('HARSH', 10, 80, 77, 75), ('PYTHON', 8, 67, 56, 45), ('DARREL', 9, 80, 80, 80))
SORTED>>>> [('DARREL', 9, 80, 80, 80), ('HARSH', 10, 80, 77, 75), ('PYTHON', 8, 67, 56, 45)]

UPDATING SUBJECT 3 MARKS
ENTER NEW MARKS FOR ALL 100
OLD LIST
[('HARSH', 10, 80, 77, 75), ('PYTHON', 8, 67, 56, 45), ('DARREL', 9, 80, 80, 80)]
NEW LIST
[('HARSH', 10, 80, 77, 100), ('PYTHON', 8, 67, 56, 100), ('DARREL', 9, 80, 80, 100)]
'''




"""
OUTPUT:
[student@localhost rollno10b]$ python 10exp3a.py
*************MENU****************
1.ADD AND PRINT N STUDENTS NAME ROLL MARKS of 3 SUBJECTS in LIST OF TUPLE
2.DISPLAY STUDENTS ROLL MARKS WHOSE NAME IS PYTHON
3.NESTED TUPLE AND SORT IT BY NAME
4.REPLACE LAST VALUE OF EVERY TUPLE IN LIST AND DISPLAY
5.EXIT
ENTER YOUR CHOICE>>>1
ENTER THE NUMBER OF STUDENTS TOU WANT>>>>3
ENTER THE NAME OF STUDENT>>>>"HARSH"
ENTER THE ROLLNO OF STUDENT>>>>10
ENTER THE MARKS1 OF STUDENT>>>>80
ENTER THE MARKS2 OF STUDENT>>>>77
ENTER THE MARKS3 OF STUDENT>>>>75
ENTER THE NAME OF STUDENT>>>>"PYTHON"
ENTER THE ROLLNO OF STUDENT>>>>8
ENTER THE MARKS1 OF STUDENT>>>>67
ENTER THE MARKS2 OF STUDENT>>>>56
ENTER THE MARKS3 OF STUDENT>>>>45
ENTER THE NAME OF STUDENT>>>>"DARREL"
ENTER THE ROLLNO OF STUDENT>>>>9
ENTER THE MARKS1 OF STUDENT>>>>80
ENTER THE MARKS2 OF STUDENT>>>>80
ENTER THE MARKS3 OF STUDENT>>>>80
[('HARSH', 10, 80, 77, 75), ('PYTHON', 8, 67, 56, 45), ('DARREL', 9, 80, 80, 80)]
*************MENU****************
1.ADD AND PRINT N STUDENTS NAME ROLL MARKS of 3 SUBJECTS in LIST OF TUPLE
2.DISPLAY STUDENTS ROLL MARKS WHOSE NAME IS PYTHON
3.NESTED TUPLE AND SORT IT BY NAME
4.REPLACE LAST VALUE OF EVERY TUPLE IN LIST AND DISPLAY
5.EXIT
ENTER YOUR CHOICE>>>2
DETAILS OF STUDENT PYTHON IN YOUR LIST
ROLL NO>>> 8
MARKS 1>>> 67
MARKS 2>>> 56
MARKS 3>>> 45
*************MENU****************
1.ADD AND PRINT N STUDENTS NAME ROLL MARKS of 3 SUBJECTS in LIST OF TUPLE
2.DISPLAY STUDENTS ROLL MARKS WHOSE NAME IS PYTHON
3.NESTED TUPLE AND SORT IT BY NAME
4.REPLACE LAST VALUE OF EVERY TUPLE IN LIST AND DISPLAY
5.EXIT
ENTER YOUR CHOICE>>>3
SORTING AS PER NAME
THE NEW TUPLE
(('HARSH', 10, 80, 77, 75), ('PYTHON', 8, 67, 56, 45), ('DARREL', 9, 80, 80, 80))
SORTED>>>> [('DARREL', 9, 80, 80, 80), ('HARSH', 10, 80, 77, 75), ('PYTHON', 8, 67, 56, 45)]
*************MENU****************
1.ADD AND PRINT N STUDENTS NAME ROLL MARKS of 3 SUBJECTS in LIST OF TUPLE
2.DISPLAY STUDENTS ROLL MARKS WHOSE NAME IS PYTHON
3.NESTED TUPLE AND SORT IT BY NAME
4.REPLACE LAST VALUE OF EVERY TUPLE IN LIST AND DISPLAY
5.EXIT
ENTER YOUR CHOICE>>>4
UPDATING SUBJECT 3 MARKS
ENTER NEW MARKS FOR ALL 67
OLD LIST
[('HARSH', 10, 80, 77, 75), ('PYTHON', 8, 67, 56, 45), ('DARREL', 9, 80, 80, 80)]
NEW LIST

[('HARSH', 10, 80, 77, 67), ('PYTHON', 8, 67, 56, 67), ('DARREL', 9, 80, 80, 67)]
*************MENU****************
1.ADD AND PRINT N STUDENTS NAME ROLL MARKS of 3 SUBJECTS in LIST OF TUPLE
2.DISPLAY STUDENTS ROLL MARKS WHOSE NAME IS PYTHON
3.NESTED TUPLE AND SORT IT BY NAME
4.REPLACE LAST VALUE OF EVERY TUPLE IN LIST AND DISPLAY
5.EXIT
ENTER YOUR CHOICE>>>5
EXIT!!
"""
